repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v5.0.0
  hooks:
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: detect-private-key
  - id: debug-statements
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.37.1
  hooks:
  - id: yamllint
    files: \.(yaml|yml)$
    types: [file, yaml]
    entry: yamllint --strict
- repo: https://github.com/ansible/ansible-lint
  rev: v25.4.0
  hooks:
  - id: ansible-lint
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.18.1
  hooks:
  - id: markdownlint-cli2
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint-docker
